CONFIG_LOG=y
CONFIG_GPIO=y
CONFIG_SERIAL=y
CONFIG_REBOOT=y
CONFIG_UART_INTERRUPT_DRIVEN=y

CONFIG_PWM=y
CONFIG_COUNTER=y

# Additional stack space for the main
# thread to handle long IR inputs
CONFIG_MAIN_STACK_SIZE=8192
